// src/main/webapp/app/entities/soft-skill/soft-skill-detail.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './soft-skill.reducer';
import { ISoftSkill } from 'app/shared/model/soft-skill.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface ISoftSkillDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export class SoftSkillDetail extends React.Component<ISoftSkillDetailProps> {
  componentDidMount() {
    this.props.getEntity(this.props.match.params.id);
  }

  render() {
    const { softSkillEntity } = this.props;
    return (
      <Row>
        <Col md="8">
          <h2>
            <Translate contentKey="talentPipeFrontendApp.softSkill.detail.title">SoftSkill</Translate> [<b>{softSkillEntity.id}</b>]
          </h2>
          <dl className="jh-entity-details">
            <dt>
              <span id="name">
                <Translate contentKey="talentPipeFrontendApp.softSkill.name">Name</Translate>
              </span>
            </dt>
            <dd>{softSkillEntity.name}</dd>
            <dt>
              <span id="description">
                <Translate contentKey="talentPipeFrontendApp.softSkill.description">Description</Translate>
              </span>
            </dt>
            <dd>{softSkillEntity.description}</dd>
          </dl>
          <Button tag={Link} to="/entity/soft-skill" replace color="info">
            <FontAwesomeIcon icon="arrow-left" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.back">Back</Translate>
            </span>
          </Button>
          &nbsp;
          <Button tag={Link} to={`/entity/soft-skill/${softSkillEntity.id}/edit`} replace color="primary">
            <FontAwesomeIcon icon="pencil-alt" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.edit">Edit</Translate>
            </span>
          </Button>
        </Col>
      </Row>
    );
  }
}

const mapStateToProps = ({ softSkill }: IRootState) => ({
  softSkillEntity: softSkill.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(SoftSkillDetail);

// src/main/webapp/app/entities/soft-skill/soft-skill-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { ISoftSkill } from 'app/shared/model/soft-skill.model';

@Component({
    selector: 'jhi-soft-skill-detail',
    templateUrl: './soft-skill-detail.component.html'
})
export class SoftSkillDetailComponent implements OnInit {
    softSkill: ISoftSkill;

    constructor(private activatedRoute: ActivatedRoute) {}

    ngOnInit() {
        this.activatedRoute.data.subscribe(({ softSkill }) => {
            this.softSkill = softSkill;
        });
    }

    previousState() {
        window.history.back();
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="softSkill">
            <h2><span jhiTranslate="talentpipeFrontendApp.softSkill.detail.title">Soft Skill</span> {{softSkill.id}}</h2>
            <hr>
            <jhi-alert-error></jhi-alert-error>
            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="talentpipeFrontendApp.softSkill.name">Name</span></dt>
                <dd>
                    <span>{{softSkill.name}}</span>
                </dd>
                <dt><span jhiTranslate="talentpipeFrontendApp.softSkill.description">Description</span></dt>
                <dd>
                    <span>{{softSkill.description}}</span>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon [icon]="'arrow-left'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back"> Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/soft-skill', softSkill.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon [icon]="'pencil-alt'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit"> Edit</span>
            </button>
        </div>
    </div>
</div>
