// src/main/webapp/app/entities/company/company-update.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
// tslint:disable-next-line:no-unused-variable
import { Translate, translate, ICrudGetAction, ICrudGetAllAction, ICrudPutAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { IUser } from 'app/shared/model/user.model';
import { getUsers } from 'app/modules/administration/user-management/user-management.reducer';
import { ISector } from 'app/shared/model/sector.model';
import { getEntities as getSectors } from 'app/entities/sector/sector.reducer';
import { ICity } from 'app/shared/model/city.model';
import { getEntities as getCities } from 'app/entities/city/city.reducer';
import { ICompanyType } from 'app/shared/model/company-type.model';
import { getEntities as getCompanyTypes } from 'app/entities/company-type/company-type.reducer';
import { getEntity, updateEntity, createEntity, reset } from './company.reducer';
import { ICompany } from 'app/shared/model/company.model';
// tslint:disable-next-line:no-unused-variable
import { convertDateTimeFromServer } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface ICompanyUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export interface ICompanyUpdateState {
  isNew: boolean;
  mainUserId: string;
  sectorId: string;
  cityId: string;
  companyTypeId: string;
}

export class CompanyUpdate extends React.Component<ICompanyUpdateProps, ICompanyUpdateState> {
  constructor(props) {
    super(props);
    this.state = {
      mainUserId: '0',
      sectorId: '0',
      cityId: '0',
      companyTypeId: '0',
      isNew: !this.props.match.params || !this.props.match.params.id
    };
  }

  componentWillUpdate(nextProps, nextState) {
    if (nextProps.updateSuccess !== this.props.updateSuccess && nextProps.updateSuccess) {
      this.handleClose();
    }
  }

  componentDidMount() {
    if (this.state.isNew) {
      this.props.reset();
    } else {
      this.props.getEntity(this.props.match.params.id);
    }

    this.props.getUsers();
    this.props.getSectors();
    this.props.getCities();
    this.props.getCompanyTypes();
  }

  saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const { companyEntity } = this.props;
      const entity = {
        ...companyEntity,
        ...values
      };

      if (this.state.isNew) {
        this.props.createEntity(entity);
      } else {
        this.props.updateEntity(entity);
      }
    }
  };

  handleClose = () => {
    this.props.history.push('/entity/company');
  };

  render() {
    const { companyEntity, users, sectors, cities, companyTypes, loading, updating } = this.props;
    const { isNew } = this.state;

    return (
      <div>
        <Row className="justify-content-center">
          <Col md="8">
            <h2 id="talentPipeFrontendApp.company.home.createOrEditLabel">
              <Translate contentKey="talentPipeFrontendApp.company.home.createOrEditLabel">Create or edit a Company</Translate>
            </h2>
          </Col>
        </Row>
        <Row className="justify-content-center">
          <Col md="8">
            {loading ? (
              <p>Loading...</p>
            ) : (
              <AvForm model={isNew ? {} : companyEntity} onSubmit={this.saveEntity}>
                {!isNew ? (
                  <AvGroup>
                    <Label for="id">
                      <Translate contentKey="global.field.id">ID</Translate>
                    </Label>
                    <AvInput id="company-id" type="text" className="form-control" name="id" required readOnly />
                  </AvGroup>
                ) : null}
                <AvGroup>
                  <Label id="taxNameLabel" for="taxName">
                    <Translate contentKey="talentPipeFrontendApp.company.taxName">Tax Name</Translate>
                  </Label>
                  <AvField
                    id="company-taxName"
                    type="text"
                    name="taxName"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="taxIdLabel" for="taxId">
                    <Translate contentKey="talentPipeFrontendApp.company.taxId">Tax Id</Translate>
                  </Label>
                  <AvField
                    id="company-taxId"
                    type="text"
                    name="taxId"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="emailLabel" for="email">
                    <Translate contentKey="talentPipeFrontendApp.company.email">Email</Translate>
                  </Label>
                  <AvField
                    id="company-email"
                    type="text"
                    name="email"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="nameLabel" for="name">
                    <Translate contentKey="talentPipeFrontendApp.company.name">Name</Translate>
                  </Label>
                  <AvField id="company-name" type="text" name="name" />
                </AvGroup>
                <AvGroup>
                  <Label id="streetLabel" for="street">
                    <Translate contentKey="talentPipeFrontendApp.company.street">Street</Translate>
                  </Label>
                  <AvField
                    id="company-street"
                    type="text"
                    name="street"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="floorLabel" for="floor">
                    <Translate contentKey="talentPipeFrontendApp.company.floor">Floor</Translate>
                  </Label>
                  <AvField id="company-floor" type="string" className="form-control" name="floor" />
                </AvGroup>
                <AvGroup>
                  <Label id="numberLabel" for="number">
                    <Translate contentKey="talentPipeFrontendApp.company.number">Number</Translate>
                  </Label>
                  <AvField
                    id="company-number"
                    type="string"
                    className="form-control"
                    name="number"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') },
                      number: { value: true, errorMessage: translate('entity.validation.number') }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="apartmentLabel" for="apartment">
                    <Translate contentKey="talentPipeFrontendApp.company.apartment">Apartment</Translate>
                  </Label>
                  <AvField id="company-apartment" type="text" name="apartment" />
                </AvGroup>
                <AvGroup>
                  <Label id="postalCodeLabel" for="postalCode">
                    <Translate contentKey="talentPipeFrontendApp.company.postalCode">Postal Code</Translate>
                  </Label>
                  <AvField
                    id="company-postalCode"
                    type="text"
                    name="postalCode"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="phoneLabel" for="phone">
                    <Translate contentKey="talentPipeFrontendApp.company.phone">Phone</Translate>
                  </Label>
                  <AvField
                    id="company-phone"
                    type="text"
                    name="phone"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label id="contactNameLabel" for="contactName">
                    <Translate contentKey="talentPipeFrontendApp.company.contactName">Contact Name</Translate>
                  </Label>
                  <AvField
                    id="company-contactName"
                    type="text"
                    name="contactName"
                    validate={{
                      required: { value: true, errorMessage: translate('entity.validation.required') }
                    }}
                  />
                </AvGroup>
                <AvGroup>
                  <Label for="mainUser.login">
                    <Translate contentKey="talentPipeFrontendApp.company.mainUser">Main User</Translate>
                  </Label>
                  <AvInput
                    id="company-mainUser"
                    type="select"
                    className="form-control"
                    name="mainUser.id"
                    value={isNew ? users[0] && users[0].id : companyEntity.mainUser.id}
                  >
                    {users
                      ? users.map(otherEntity => (
                          <option value={otherEntity.id} key={otherEntity.id}>
                            {otherEntity.login}
                          </option>
                        ))
                      : null}
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <Label for="sector.name">
                    <Translate contentKey="talentPipeFrontendApp.company.sector">Sector</Translate>
                  </Label>
                  <AvInput
                    id="company-sector"
                    type="select"
                    className="form-control"
                    name="sector.id"
                    value={isNew ? sectors[0] && sectors[0].id : companyEntity.sector.id}
                  >
                    {sectors
                      ? sectors.map(otherEntity => (
                          <option value={otherEntity.id} key={otherEntity.id}>
                            {otherEntity.name}
                          </option>
                        ))
                      : null}
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <Label for="city.name">
                    <Translate contentKey="talentPipeFrontendApp.company.city">City</Translate>
                  </Label>
                  <AvInput
                    id="company-city"
                    type="select"
                    className="form-control"
                    name="city.id"
                    value={isNew ? cities[0] && cities[0].id : companyEntity.city.id}
                  >
                    {cities
                      ? cities.map(otherEntity => (
                          <option value={otherEntity.id} key={otherEntity.id}>
                            {otherEntity.name}
                          </option>
                        ))
                      : null}
                  </AvInput>
                </AvGroup>
                <AvGroup>
                  <Label for="companyType.name">
                    <Translate contentKey="talentPipeFrontendApp.company.companyType">Company Type</Translate>
                  </Label>
                  <AvInput
                    id="company-companyType"
                    type="select"
                    className="form-control"
                    name="companyType.id"
                    value={isNew ? companyTypes[0] && companyTypes[0].id : companyEntity.companyType.id}
                  >
                    {companyTypes
                      ? companyTypes.map(otherEntity => (
                          <option value={otherEntity.id} key={otherEntity.id}>
                            {otherEntity.name}
                          </option>
                        ))
                      : null}
                  </AvInput>
                </AvGroup>
                <Button tag={Link} id="cancel-save" to="/entity/company" replace color="info">
                  <FontAwesomeIcon icon="arrow-left" />
                  &nbsp;
                  <span className="d-none d-md-inline">
                    <Translate contentKey="entity.action.back">Back</Translate>
                  </span>
                </Button>
                &nbsp;
                <Button color="primary" id="save-entity" type="submit" disabled={updating}>
                  <FontAwesomeIcon icon="save" />
                  &nbsp;
                  <Translate contentKey="entity.action.save">Save</Translate>
                </Button>
              </AvForm>
            )}
          </Col>
        </Row>
      </div>
    );
  }
}

const mapStateToProps = (storeState: IRootState) => ({
  users: storeState.userManagement.users,
  sectors: storeState.sector.entities,
  cities: storeState.city.entities,
  companyTypes: storeState.companyType.entities,
  companyEntity: storeState.company.entity,
  loading: storeState.company.loading,
  updating: storeState.company.updating,
  updateSuccess: storeState.company.updateSuccess
});

const mapDispatchToProps = {
  getUsers,
  getSectors,
  getCities,
  getCompanyTypes,
  getEntity,
  updateEntity,
  createEntity,
  reset
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(CompanyUpdate);

// src/main/webapp/app/entities/company/company-update.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { JhiAlertService } from 'ng-jhipster';

import { ICompany } from 'app/shared/model/company.model';
import { CompanyService } from './company.service';
import { IUser, UserService } from 'app/core';
import { ISector } from 'app/shared/model/sector.model';
import { SectorService } from 'app/entities/sector';
import { ICity } from 'app/shared/model/city.model';
import { CityService } from 'app/entities/city';
import { ICompanyType } from 'app/shared/model/company-type.model';
import { CompanyTypeService } from 'app/entities/company-type';

@Component({
    selector: 'jhi-company-update',
    templateUrl: './company-update.component.html'
})
export class CompanyUpdateComponent implements OnInit {
    company: ICompany;
    isSaving: boolean;

    users: IUser[];

    sectors: ISector[];

    cities: ICity[];

    companytypes: ICompanyType[];

    constructor(
        private jhiAlertService: JhiAlertService,
        private companyService: CompanyService,
        private userService: UserService,
        private sectorService: SectorService,
        private cityService: CityService,
        private companyTypeService: CompanyTypeService,
        private activatedRoute: ActivatedRoute
    ) {}

    ngOnInit() {
        this.isSaving = false;
        this.activatedRoute.data.subscribe(({ company }) => {
            this.company = company;
        });
        this.userService.query().subscribe(
            (res: HttpResponse<IUser[]>) => {
                this.users = res.body;
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
        this.sectorService.query().subscribe(
            (res: HttpResponse<ISector[]>) => {
                this.sectors = res.body;
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
        this.cityService.query().subscribe(
            (res: HttpResponse<ICity[]>) => {
                this.cities = res.body;
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
        this.companyTypeService.query().subscribe(
            (res: HttpResponse<ICompanyType[]>) => {
                this.companytypes = res.body;
            },
            (res: HttpErrorResponse) => this.onError(res.message)
        );
    }

    previousState() {
        window.history.back();
    }

    save() {
        this.isSaving = true;
        if (this.company.id !== undefined) {
            this.subscribeToSaveResponse(this.companyService.update(this.company));
        } else {
            this.subscribeToSaveResponse(this.companyService.create(this.company));
        }
    }

    private subscribeToSaveResponse(result: Observable<HttpResponse<ICompany>>) {
        result.subscribe((res: HttpResponse<ICompany>) => this.onSaveSuccess(), (res: HttpErrorResponse) => this.onSaveError());
    }

    private onSaveSuccess() {
        this.isSaving = false;
        this.previousState();
    }

    private onSaveError() {
        this.isSaving = false;
    }

    private onError(errorMessage: string) {
        this.jhiAlertService.error(errorMessage, null, null);
    }

    trackUserById(index: number, item: IUser) {
        return item.id;
    }

    trackSectorById(index: number, item: ISector) {
        return item.id;
    }

    trackCityById(index: number, item: ICity) {
        return item.id;
    }

    trackCompanyTypeById(index: number, item: ICompanyType) {
        return item.id;
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" #editForm="ngForm">
            <h2 id="jhi-company-heading" jhiTranslate="talentpipeFrontendApp.company.home.createOrEditLabel">Create or edit a Company</h2>
            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group" [hidden]="!company.id">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id"
                        [(ngModel)]="company.id" readonly />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="talentpipeFrontendApp.company.taxName" for="field_taxName">Tax Name</label>
                    <input type="text" class="form-control" name="taxName" id="field_taxName"
                        [(ngModel)]="company.taxName" required/>
                    <div [hidden]="!(editForm.controls.taxName?.dirty && editForm.controls.taxName?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.taxName?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="talentpipeFrontendApp.company.taxId" for="field_taxId">Tax Id</label>
                    <input type="text" class="form-control" name="taxId" id="field_taxId"
                        [(ngModel)]="company.taxId" required/>
                    <div [hidden]="!(editForm.controls.taxId?.dirty && editForm.controls.taxId?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.taxId?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="talentpipeFrontendApp.company.email" for="field_email">Email</label>
                    <input type="text" class="form-control" name="email" id="field_email"
                        [(ngModel)]="company.email" required/>
                    <div [hidden]="!(editForm.controls.email?.dirty && editForm.controls.email?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.email?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="talentpipeFrontendApp.company.name" for="field_name">Name</label>
                    <input type="text" class="form-control" name="name" id="field_name"
                        [(ngModel)]="company.name" />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="talentpipeFrontendApp.company.street" for="field_street">Street</label>
                    <input type="text" class="form-control" name="street" id="field_street"
                        [(ngModel)]="company.street" required/>
                    <div [hidden]="!(editForm.controls.street?.dirty && editForm.controls.street?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.street?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="talentpipeFrontendApp.company.floor" for="field_floor">Floor</label>
                    <input type="number" class="form-control" name="floor" id="field_floor"
                        [(ngModel)]="company.floor" />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="talentpipeFrontendApp.company.number" for="field_number">Number</label>
                    <input type="number" class="form-control" name="number" id="field_number"
                        [(ngModel)]="company.number" required/>
                    <div [hidden]="!(editForm.controls.number?.dirty && editForm.controls.number?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.number?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                        <small class="form-text text-danger"
                            [hidden]="!editForm.controls.number?.errors?.number" jhiTranslate="entity.validation.number">
                            This field should be a number.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="talentpipeFrontendApp.company.apartment" for="field_apartment">Apartment</label>
                    <input type="text" class="form-control" name="apartment" id="field_apartment"
                        [(ngModel)]="company.apartment" />
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="talentpipeFrontendApp.company.postalCode" for="field_postalCode">Postal Code</label>
                    <input type="text" class="form-control" name="postalCode" id="field_postalCode"
                        [(ngModel)]="company.postalCode" required/>
                    <div [hidden]="!(editForm.controls.postalCode?.dirty && editForm.controls.postalCode?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.postalCode?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="talentpipeFrontendApp.company.phone" for="field_phone">Phone</label>
                    <input type="text" class="form-control" name="phone" id="field_phone"
                        [(ngModel)]="company.phone" required/>
                    <div [hidden]="!(editForm.controls.phone?.dirty && editForm.controls.phone?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.phone?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="talentpipeFrontendApp.company.contactName" for="field_contactName">Contact Name</label>
                    <input type="text" class="form-control" name="contactName" id="field_contactName"
                        [(ngModel)]="company.contactName" required/>
                    <div [hidden]="!(editForm.controls.contactName?.dirty && editForm.controls.contactName?.invalid)">
                        <small class="form-text text-danger"
                        [hidden]="!editForm.controls.contactName?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                        </small>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="talentpipeFrontendApp.company.mainUser" for="field_mainUser">Main User</label>
                    <select class="form-control" id="field_mainUser" name="mainUser" [(ngModel)]="company.mainUser"  required>
                        <option *ngIf="!editForm.value.mainUser" [ngValue]="null" selected></option>
                        <option [ngValue]="userOption.id === company.mainUser?.id ? company.mainUser : userOption" *ngFor="let userOption of users; trackBy: trackUserById">{{userOption.login}}</option>
                    </select>
                </div>
                <div [hidden]="!(editForm.controls.mainUser?.dirty && editForm.controls.mainUser?.invalid)">
                    <small class="form-text text-danger"
                        [hidden]="!editForm.controls.mainUser?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                    </small>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="talentpipeFrontendApp.company.sector" for="field_sector">Sector</label>
                    <select class="form-control" id="field_sector" name="sector" [(ngModel)]="company.sector"  required>
                        <option *ngIf="!editForm.value.sector" [ngValue]="null" selected></option>
                        <option [ngValue]="sectorOption.id === company.sector?.id ? company.sector : sectorOption" *ngFor="let sectorOption of sectors; trackBy: trackSectorById">{{sectorOption.name}}</option>
                    </select>
                </div>
                <div [hidden]="!(editForm.controls.sector?.dirty && editForm.controls.sector?.invalid)">
                    <small class="form-text text-danger"
                        [hidden]="!editForm.controls.sector?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                    </small>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="talentpipeFrontendApp.company.city" for="field_city">City</label>
                    <select class="form-control" id="field_city" name="city" [(ngModel)]="company.city"  required>
                        <option *ngIf="!editForm.value.city" [ngValue]="null" selected></option>
                        <option [ngValue]="cityOption.id === company.city?.id ? company.city : cityOption" *ngFor="let cityOption of cities; trackBy: trackCityById">{{cityOption.name}}</option>
                    </select>
                </div>
                <div [hidden]="!(editForm.controls.city?.dirty && editForm.controls.city?.invalid)">
                    <small class="form-text text-danger"
                        [hidden]="!editForm.controls.city?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                    </small>
                </div>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="talentpipeFrontendApp.company.companyType" for="field_companyType">Company Type</label>
                    <select class="form-control" id="field_companyType" name="companyType" [(ngModel)]="company.companyType"  required>
                        <option *ngIf="!editForm.value.companyType" [ngValue]="null" selected></option>
                        <option [ngValue]="companyTypeOption.id === company.companyType?.id ? company.companyType : companyTypeOption" *ngFor="let companyTypeOption of companytypes; trackBy: trackCompanyTypeById">{{companyTypeOption.name}}</option>
                    </select>
                </div>
                <div [hidden]="!(editForm.controls.companyType?.dirty && editForm.controls.companyType?.invalid)">
                    <small class="form-text text-danger"
                        [hidden]="!editForm.controls.companyType?.errors?.required" jhiTranslate="entity.validation.required">
                        This field is required.
                    </small>
                </div>
            </div>
            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary"  (click)="previousState()">
                    <fa-icon [icon]="'ban'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>
                <button type="submit" id="save-entity" [disabled]="editForm.form.invalid || isSaving" class="btn btn-primary">
                    <fa-icon [icon]="'save'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
