// src/main/webapp/app/entities/state-before-tax/state-before-tax-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IStateBeforeTax } from 'app/shared/model/state-before-tax.model';

@Component({
    selector: 'jhi-state-before-tax-detail',
    templateUrl: './state-before-tax-detail.component.html'
})
export class StateBeforeTaxDetailComponent implements OnInit {
    stateBeforeTax: IStateBeforeTax;

    constructor(private activatedRoute: ActivatedRoute) {}

    ngOnInit() {
        this.activatedRoute.data.subscribe(({ stateBeforeTax }) => {
            this.stateBeforeTax = stateBeforeTax;
        });
    }

    previousState() {
        window.history.back();
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="stateBeforeTax">
            <h2><span jhiTranslate="talentpipeFrontendApp.stateBeforeTax.detail.title">State Before Tax</span> {{stateBeforeTax.id}}</h2>
            <hr>
            <jhi-alert-error></jhi-alert-error>
            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="talentpipeFrontendApp.stateBeforeTax.name">Name</span></dt>
                <dd>
                    <span>{{stateBeforeTax.name}}</span>
                </dd>
                <dt><span jhiTranslate="talentpipeFrontendApp.stateBeforeTax.description">Description</span></dt>
                <dd>
                    <span>{{stateBeforeTax.description}}</span>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon [icon]="'arrow-left'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back"> Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/state-before-tax', stateBeforeTax.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon [icon]="'pencil-alt'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit"> Edit</span>
            </button>
        </div>
    </div>
</div>

// src/main/webapp/app/entities/state-before-tax/state-before-tax-detail.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './state-before-tax.reducer';
import { IStateBeforeTax } from 'app/shared/model/state-before-tax.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IStateBeforeTaxDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export class StateBeforeTaxDetail extends React.Component<IStateBeforeTaxDetailProps> {
  componentDidMount() {
    this.props.getEntity(this.props.match.params.id);
  }

  render() {
    const { stateBeforeTaxEntity } = this.props;
    return (
      <Row>
        <Col md="8">
          <h2>
            <Translate contentKey="talentPipeFrontendApp.stateBeforeTax.detail.title">StateBeforeTax</Translate> [
            <b>{stateBeforeTaxEntity.id}</b>]
          </h2>
          <dl className="jh-entity-details">
            <dt>
              <span id="name">
                <Translate contentKey="talentPipeFrontendApp.stateBeforeTax.name">Name</Translate>
              </span>
            </dt>
            <dd>{stateBeforeTaxEntity.name}</dd>
            <dt>
              <span id="description">
                <Translate contentKey="talentPipeFrontendApp.stateBeforeTax.description">Description</Translate>
              </span>
            </dt>
            <dd>{stateBeforeTaxEntity.description}</dd>
          </dl>
          <Button tag={Link} to="/entity/state-before-tax" replace color="info">
            <FontAwesomeIcon icon="arrow-left" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.back">Back</Translate>
            </span>
          </Button>
          &nbsp;
          <Button tag={Link} to={`/entity/state-before-tax/${stateBeforeTaxEntity.id}/edit`} replace color="primary">
            <FontAwesomeIcon icon="pencil-alt" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.edit">Edit</Translate>
            </span>
          </Button>
        </Col>
      </Row>
    );
  }
}

const mapStateToProps = ({ stateBeforeTax }: IRootState) => ({
  stateBeforeTaxEntity: stateBeforeTax.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(StateBeforeTaxDetail);
