// src/main/webapp/app/entities/technical-skill/technical-skill-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { ITechnicalSkill } from 'app/shared/model/technical-skill.model';

@Component({
    selector: 'jhi-technical-skill-detail',
    templateUrl: './technical-skill-detail.component.html'
})
export class TechnicalSkillDetailComponent implements OnInit {
    technicalSkill: ITechnicalSkill;

    constructor(private activatedRoute: ActivatedRoute) {}

    ngOnInit() {
        this.activatedRoute.data.subscribe(({ technicalSkill }) => {
            this.technicalSkill = technicalSkill;
        });
    }

    previousState() {
        window.history.back();
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="technicalSkill">
            <h2><span jhiTranslate="talentpipeFrontendApp.technicalSkill.detail.title">Technical Skill</span> {{technicalSkill.id}}</h2>
            <hr>
            <jhi-alert-error></jhi-alert-error>
            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="talentpipeFrontendApp.technicalSkill.name">Name</span></dt>
                <dd>
                    <span>{{technicalSkill.name}}</span>
                </dd>
                <dt><span jhiTranslate="talentpipeFrontendApp.technicalSkill.description">Description</span></dt>
                <dd>
                    <span>{{technicalSkill.description}}</span>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon [icon]="'arrow-left'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back"> Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/technical-skill', technicalSkill.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon [icon]="'pencil-alt'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit"> Edit</span>
            </button>
        </div>
    </div>
</div>

// src/main/webapp/app/entities/technical-skill/technical-skill-detail.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './technical-skill.reducer';
import { ITechnicalSkill } from 'app/shared/model/technical-skill.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface ITechnicalSkillDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export class TechnicalSkillDetail extends React.Component<ITechnicalSkillDetailProps> {
  componentDidMount() {
    this.props.getEntity(this.props.match.params.id);
  }

  render() {
    const { technicalSkillEntity } = this.props;
    return (
      <Row>
        <Col md="8">
          <h2>
            <Translate contentKey="talentPipeFrontendApp.technicalSkill.detail.title">TechnicalSkill</Translate> [
            <b>{technicalSkillEntity.id}</b>]
          </h2>
          <dl className="jh-entity-details">
            <dt>
              <span id="name">
                <Translate contentKey="talentPipeFrontendApp.technicalSkill.name">Name</Translate>
              </span>
            </dt>
            <dd>{technicalSkillEntity.name}</dd>
            <dt>
              <span id="description">
                <Translate contentKey="talentPipeFrontendApp.technicalSkill.description">Description</Translate>
              </span>
            </dt>
            <dd>{technicalSkillEntity.description}</dd>
          </dl>
          <Button tag={Link} to="/entity/technical-skill" replace color="info">
            <FontAwesomeIcon icon="arrow-left" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.back">Back</Translate>
            </span>
          </Button>
          &nbsp;
          <Button tag={Link} to={`/entity/technical-skill/${technicalSkillEntity.id}/edit`} replace color="primary">
            <FontAwesomeIcon icon="pencil-alt" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.edit">Edit</Translate>
            </span>
          </Button>
        </Col>
      </Row>
    );
  }
}

const mapStateToProps = ({ technicalSkill }: IRootState) => ({
  technicalSkillEntity: technicalSkill.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(TechnicalSkillDetail);
