// src/main/webapp/app/entities/company-type/company-type-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { ICompanyType } from 'app/shared/model/company-type.model';

@Component({
    selector: 'jhi-company-type-detail',
    templateUrl: './company-type-detail.component.html'
})
export class CompanyTypeDetailComponent implements OnInit {
    companyType: ICompanyType;

    constructor(private activatedRoute: ActivatedRoute) {}

    ngOnInit() {
        this.activatedRoute.data.subscribe(({ companyType }) => {
            this.companyType = companyType;
        });
    }

    previousState() {
        window.history.back();
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="companyType">
            <h2><span jhiTranslate="talentpipeFrontendApp.companyType.detail.title">Company Type</span> {{companyType.id}}</h2>
            <hr>
            <jhi-alert-error></jhi-alert-error>
            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="talentpipeFrontendApp.companyType.name">Name</span></dt>
                <dd>
                    <span>{{companyType.name}}</span>
                </dd>
                <dt><span jhiTranslate="talentpipeFrontendApp.companyType.description">Description</span></dt>
                <dd>
                    <span>{{companyType.description}}</span>
                </dd>
                <dt><span jhiTranslate="talentpipeFrontendApp.companyType.minEmployeesQuantity">Min Employees Quantity</span></dt>
                <dd>
                    <span>{{companyType.minEmployeesQuantity}}</span>
                </dd>
                <dt><span jhiTranslate="talentpipeFrontendApp.companyType.maxEmployeesQuantity">Max Employees Quantity</span></dt>
                <dd>
                    <span>{{companyType.maxEmployeesQuantity}}</span>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon [icon]="'arrow-left'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back"> Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/company-type', companyType.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon [icon]="'pencil-alt'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit"> Edit</span>
            </button>
        </div>
    </div>
</div>

// src/main/webapp/app/entities/company-type/company-type-detail.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './company-type.reducer';
import { ICompanyType } from 'app/shared/model/company-type.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface ICompanyTypeDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export class CompanyTypeDetail extends React.Component<ICompanyTypeDetailProps> {
  componentDidMount() {
    this.props.getEntity(this.props.match.params.id);
  }

  render() {
    const { companyTypeEntity } = this.props;
    return (
      <Row>
        <Col md="8">
          <h2>
            <Translate contentKey="talentPipeFrontendApp.companyType.detail.title">CompanyType</Translate> [<b>{companyTypeEntity.id}</b>]
          </h2>
          <dl className="jh-entity-details">
            <dt>
              <span id="name">
                <Translate contentKey="talentPipeFrontendApp.companyType.name">Name</Translate>
              </span>
            </dt>
            <dd>{companyTypeEntity.name}</dd>s
            <dt>
              <span id="description">
                <Translate contentKey="talentPipeFrontendApp.companyType.description">Description</Translate>
              </span>
            </dt>
            <dd>{companyTypeEntity.description}</dd>
            <dt>
              <span id="minEmployeesQuantity">
                <Translate contentKey="talentPipeFrontendApp.companyType.minEmployeesQuantity">Min Employees Quantity</Translate>
              </span>
            </dt>
            <dd>{companyTypeEntity.minEmployeesQuantity}</dd>
            <dt>
              <span id="maxEmployeesQuantity">
                <Translate contentKey="talentPipeFrontendApp.companyType.maxEmployeesQuantity">Max Employees Quantity</Translate>
              </span>
            </dt>
            <dd>{companyTypeEntity.maxEmployeesQuantity}</dd>
          </dl>
          <Button tag={Link} to="/entity/company-type" replace color="info">
            <FontAwesomeIcon icon="arrow-left" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.back">Back</Translate>
            </span>
          </Button>
          &nbsp;
          <Button tag={Link} to={`/entity/company-type/${companyTypeEntity.id}/edit`} replace color="primary">
            <FontAwesomeIcon icon="pencil-alt" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.edit">Edit</Translate>
            </span>
          </Button>
        </Col>
      </Row>
    );
  }
}

const mapStateToProps = ({ companyType }: IRootState) => ({
  companyTypeEntity: companyType.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(CompanyTypeDetail);
