// src/main/webapp/app/entities/search-type/search-type-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { ISearchType } from 'app/shared/model/search-type.model';

@Component({
    selector: 'jhi-search-type-detail',
    templateUrl: './search-type-detail.component.html'
})
export class SearchTypeDetailComponent implements OnInit {
    searchType: ISearchType;

    constructor(private activatedRoute: ActivatedRoute) {}

    ngOnInit() {
        this.activatedRoute.data.subscribe(({ searchType }) => {
            this.searchType = searchType;
        });
    }

    previousState() {
        window.history.back();
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="searchType">
            <h2><span jhiTranslate="talentpipeFrontendApp.searchType.detail.title">Search Type</span> {{searchType.id}}</h2>
            <hr>
            <jhi-alert-error></jhi-alert-error>
            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="talentpipeFrontendApp.searchType.name">Name</span></dt>
                <dd>
                    <span>{{searchType.name}}</span>
                </dd>
                <dt><span jhiTranslate="talentpipeFrontendApp.searchType.description">Description</span></dt>
                <dd>
                    <span>{{searchType.description}}</span>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon [icon]="'arrow-left'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back"> Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/search-type', searchType.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon [icon]="'pencil-alt'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit"> Edit</span>
            </button>
        </div>
    </div>
</div>

// src/main/webapp/app/entities/search-type/search-type-detail.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './search-type.reducer';
import { ISearchType } from 'app/shared/model/search-type.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface ISearchTypeDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export class SearchTypeDetail extends React.Component<ISearchTypeDetailProps> {
  componentDidMount() {
    this.props.getEntity(this.props.match.params.id);
  }

  render() {
    const { searchTypeEntity } = this.props;
    return (
      <Row>
        <Col md="8">
          <h2>
            <Translate contentKey="talentPipeFrontendApp.searchType.detail.title">SearchType</Translate> [<b>{searchTypeEntity.id}</b>]
          </h2>
          <dl className="jh-entity-details">
            <dt>
              <span id="name">
                <Translate contentKey="talentPipeFrontendApp.searchType.name">Name</Translate>
              </span>
            </dt>
            <dd>{searchTypeEntity.name}</dd>
            <dt>
              <span id="description">
                <Translate contentKey="talentPipeFrontendApp.searchType.description">Description</Translate>
              </span>
            </dt>
            <dd>{searchTypeEntity.description}</dd>
          </dl>
          <Button tag={Link} to="/entity/search-type" replace color="info">
            <FontAwesomeIcon icon="arrow-left" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.back">Back</Translate>
            </span>
          </Button>
          &nbsp;
          <Button tag={Link} to={`/entity/search-type/${searchTypeEntity.id}/edit`} replace color="primary">
            <FontAwesomeIcon icon="pencil-alt" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.edit">Edit</Translate>
            </span>
          </Button>
        </Col>
      </Row>
    );
  }
}

const mapStateToProps = ({ searchType }: IRootState) => ({
  searchTypeEntity: searchType.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(SearchTypeDetail);
