// src/main/webapp/app/entities/benefit/benefit-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IBenefit } from 'app/shared/model/benefit.model';

@Component({
    selector: 'jhi-benefit-detail',
    templateUrl: './benefit-detail.component.html'
})
export class BenefitDetailComponent implements OnInit {
    benefit: IBenefit;

    constructor(private activatedRoute: ActivatedRoute) {}

    ngOnInit() {
        this.activatedRoute.data.subscribe(({ benefit }) => {
            this.benefit = benefit;
        });
    }

    previousState() {
        window.history.back();
    }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="benefit">
            <h2><span jhiTranslate="talentpipeFrontendApp.benefit.detail.title">Benefit</span> {{benefit.id}}</h2>
            <hr>
            <jhi-alert-error></jhi-alert-error>
            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="talentpipeFrontendApp.benefit.name">Name</span></dt>
                <dd>
                    <span>{{benefit.name}}</span>
                </dd>
                <dt><span jhiTranslate="talentpipeFrontendApp.benefit.description">Description</span></dt>
                <dd>
                    <span>{{benefit.description}}</span>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon [icon]="'arrow-left'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back"> Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/benefit', benefit.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon [icon]="'pencil-alt'"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit"> Edit</span>
            </button>
        </div>
    </div>
</div>

// src/main/webapp/app/entities/benefit/benefit-detail.tsx
import React from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
// tslint:disable-next-line:no-unused-variable
import { Translate, ICrudGetAction } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './benefit.reducer';
import { IBenefit } from 'app/shared/model/benefit.model';
// tslint:disable-next-line:no-unused-variable
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IBenefitDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export class BenefitDetail extends React.Component<IBenefitDetailProps> {
  componentDidMount() {
    this.props.getEntity(this.props.match.params.id);
  }

  render() {
    const { benefitEntity } = this.props;
    return (
      <Row>
        <Col md="8">
          <h2>
            <Translate contentKey="talentPipeFrontendApp.benefit.detail.title">Benefit</Translate> [<b>{benefitEntity.id}</b>]
          </h2>
          <dl className="jh-entity-details">
            <dt>
              <span id="name">
                <Translate contentKey="talentPipeFrontendApp.benefit.name">Name</Translate>
              </span>
            </dt>
            <dd>{benefitEntity.name}</dd>
            <dt>
              <span id="description">
                <Translate contentKey="talentPipeFrontendApp.benefit.description">Description</Translate>
              </span>
            </dt>
            <dd>{benefitEntity.description}</dd>
          </dl>
          <Button tag={Link} to="/entity/benefit" replace color="info">
            <FontAwesomeIcon icon="arrow-left" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.back">Back</Translate>
            </span>
          </Button>
          &nbsp;
          <Button tag={Link} to={`/entity/benefit/${benefitEntity.id}/edit`} replace color="primary">
            <FontAwesomeIcon icon="pencil-alt" />{' '}
            <span className="d-none d-md-inline">
              <Translate contentKey="entity.action.edit">Edit</Translate>
            </span>
          </Button>
        </Col>
      </Row>
    );
  }
}

const mapStateToProps = ({ benefit }: IRootState) => ({
  benefitEntity: benefit.entity
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(BenefitDetail);
